/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame_pkg;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author paulo
 */
public class quizFrame extends javax.swing.JFrame {

    private final ArrayList<String> lista = new ArrayList<>();
    private int correto = 0;
    private int progresso = 1;
    private int qnt_correto = 0;
    private final String audio_path = "src/audio_pkg/";

    /**
     * Creates new form quizFrame
     */
    public quizFrame() {
        initComponents();
    }

    void nextQuest() {
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Acabaram as perguntas!! \n Respostas certas: "+qnt_correto, "Fim de Quiz!", JOptionPane.CANCEL_OPTION);
            mainFrame.saveInfo(qnt_correto);
            this.dispose();
        } else {
            String linha = lista.remove(0);
            String[] partes = linha.split("[|]");
            txtPergunta.setText(partes[0]);
            ButtonR1.setText(partes[1]);
            ButtonR2.setText(partes[2]);
            ButtonR3.setText(partes[3]);
            correto = Integer.parseInt(partes[4]);
        }
    }

    void Load() {
        String caminho = getFile();
        File arquivo = new File(caminho);
        lista.clear();
        try {
            Scanner entrada = new Scanner(arquivo);
            while (entrada.hasNext()) {
                String linha = entrada.nextLine();
                lista.add(linha); //Adiciona 
            }
            Collections.shuffle(lista); // Embaralha
            nextQuest();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro: \n" + ex,
                    "Erro de arquivo",
                    JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    boolean checkAnswer(int resposta) {
        boolean acerto = false;
        if(resposta == correto)
        {
            acerto = true;
        }
        ButtonR1.setEnabled(false);
        ButtonR2.setEnabled(false);
        ButtonR3.setEnabled(false);
        progressoProgressBar.setValue(progresso);
        progressoProgressBar.setString(progresso*10 + "%");
        progresso++;
        switch (correto) {
            case 1:
                ButtonR1.setForeground(Color.GREEN);
                ButtonR2.setForeground(Color.RED);
                ButtonR3.setForeground(Color.RED);
                break;
            case 2:
                ButtonR1.setForeground(Color.RED);
                ButtonR2.setForeground(Color.GREEN);
                ButtonR3.setForeground(Color.RED);
                break;
            case 3:
                ButtonR1.setForeground(Color.RED);
                ButtonR2.setForeground(Color.RED);
                ButtonR3.setForeground(Color.GREEN);
                break;
        }
        Thread delay = new Thread(() -> {
            try {
                Thread.sleep(2500);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
            }
            ButtonR1.setForeground(Color.BLACK);
            ButtonR2.setForeground(Color.BLACK);
            ButtonR3.setForeground(Color.BLACK);
            ButtonR1.setEnabled(true);
            ButtonR2.setEnabled(true);
            ButtonR3.setEnabled(true);
            nextQuest();
        });
        delay.start();
        return acerto;
    }

    private String getFile() {
        String file_name = mainFrame.arquivo;
        String file = "src/file_pkg/" + file_name + ".txt";
        return file;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        perguntaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPergunta = new javax.swing.JTextArea();
        LabelClose = new javax.swing.JLabel();
        respostasPanel = new javax.swing.JPanel();
        ButtonR1 = new javax.swing.JButton();
        ButtonR2 = new javax.swing.JButton();
        ButtonR3 = new javax.swing.JButton();
        progressoProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        perguntaPanel.setBackground(new java.awt.Color(26, 38, 92));
        perguntaPanel.setPreferredSize(new java.awt.Dimension(519, 90));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtPergunta.setEditable(false);
        txtPergunta.setBackground(new java.awt.Color(26, 38, 92));
        txtPergunta.setColumns(20);
        txtPergunta.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        txtPergunta.setForeground(new java.awt.Color(255, 255, 255));
        txtPergunta.setLineWrap(true);
        txtPergunta.setRows(5);
        txtPergunta.setText("Pergunta");
        txtPergunta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPergunta);

        javax.swing.GroupLayout perguntaPanelLayout = new javax.swing.GroupLayout(perguntaPanel);
        perguntaPanel.setLayout(perguntaPanelLayout);
        perguntaPanelLayout.setHorizontalGroup(
            perguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perguntaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        perguntaPanelLayout.setVerticalGroup(
            perguntaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perguntaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_pkg/close-window-24.png"))); // NOI18N
        LabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCloseMouseClicked(evt);
            }
        });

        respostasPanel.setLayout(new java.awt.GridLayout(4, 1, 30, 50));

        ButtonR1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonR1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        ButtonR1.setText("Resposta 1");
        ButtonR1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonR1ActionPerformed(evt);
            }
        });
        respostasPanel.add(ButtonR1);

        ButtonR2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonR2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        ButtonR2.setText("Resposta 2");
        ButtonR2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonR2ActionPerformed(evt);
            }
        });
        respostasPanel.add(ButtonR2);

        ButtonR3.setBackground(new java.awt.Color(255, 255, 255));
        ButtonR3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        ButtonR3.setText("Resposta 3");
        ButtonR3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ButtonR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonR3ActionPerformed(evt);
            }
        });
        respostasPanel.add(ButtonR3);

        progressoProgressBar.setForeground(new java.awt.Color(0, 0, 0));
        progressoProgressBar.setMaximum(10);
        progressoProgressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        progressoProgressBar.setStringPainted(true);
        respostasPanel.add(progressoProgressBar);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respostasPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(perguntaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelClose)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perguntaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(respostasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_LabelCloseMouseClicked

    private void ButtonR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonR2ActionPerformed
        if(checkAnswer(2))
        {
            qnt_correto++;
        }
    }//GEN-LAST:event_ButtonR2ActionPerformed

    private void ButtonR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonR3ActionPerformed
        if(checkAnswer(3))
        {
            qnt_correto++;
        }
    }//GEN-LAST:event_ButtonR3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Load();
    }//GEN-LAST:event_formWindowOpened

    private void ButtonR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonR1ActionPerformed
        if(checkAnswer(1))
        {
            qnt_correto++;
        }
    }//GEN-LAST:event_ButtonR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new quizFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ButtonR1;
    public static javax.swing.JButton ButtonR2;
    public static javax.swing.JButton ButtonR3;
    private javax.swing.JLabel LabelClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel perguntaPanel;
    private javax.swing.JProgressBar progressoProgressBar;
    private javax.swing.JPanel respostasPanel;
    private javax.swing.JTextArea txtPergunta;
    // End of variables declaration//GEN-END:variables

}
